apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: iyzyjyk84-nodejs
  janus-idp.io/tekton: iyzyjyk84-nodejs
  backstage.io/kubernetes-id: iyzyjyk84-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: iyzyjyk84-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
