apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: iyzyjyk84-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: iyzyjyk84-nodejs 
  name: iyzyjyk84-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: iyzyjyk84-nodejs 
